name: enfugue
channels:
  - pytorch
  - defaults
  - nvidia
  - nvidia/label/cuda-11.7.1
  - conda-forge
dependencies:
  - python=3.10.9
  - pip=22.3
  - cudatoolkit=11.7
  - pytorch=1.13.1
  - torchvision=0.14.1
  - numpy=1.24.3
  - pip:
    - nvidia-pyindex>=1.0.9
    - pibble[cherrypy]>=0.6
    - numpy>=1.24.3
    - colored>=1.4,<1.5
    - diffusers>=0.16,<0.17
    - albumentations>=0.4.3,<0.5
    - opencv-python>=4.7.0.72,<4.8
    - pudb==2019.2
    - invisible-watermark>=0.1,<0.2
    - imageio>=2.9,<3.0
    - imageio-ffmpeg>=0.4.2,<0.5
    - pytorch-lightning>=2.0.2,<2.1
    - omegaconf>=2.1.1,<2.2
    - test-tube>=0.7.5,<0.8
    - streamlit>=0.73,<0.75
    - einops>=0.3,<0.4
    - torch-fidelity>=0.3,<0.4
    - transformers>=4.28,<5.0
    - torchmetrics>=0.11.4,<0.12
    - kornia>=0.6,<0.7
    - polygraphy>=0.47,<0.48
    - accelerate>=0.18<0.19
    - gputil>=1.4,<1.5
    - safetensors>=0.3,<0.4
    - git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - git+https://github.com/openai/CLIP.git@main#egg=clip
    - git+https://github.com/CompVis/stable-diffusion.git@main#egg=latent-diffusion
    - --extra-index-url https://download.pytorch.org/whl/cu117
    - torch==1.13.1+cu117
