---
noauth: false
safe: true
queue: 4
width: 512
height: 512
engine:
    root: ~/.cache/enfugue
    logging:
        handler: file
        file: ~/.cache/enfugue-engine.log
        level: debug
        silenced:
            - sqlalchemy.pool.impl.NullPool
downloads:
    concurrent: 2
    queue: 10
