---
colored: true
handler: stream
stream: stdout
level: debug
silenced:
    - sqlalchemy.pool.impl.NullPool
    - http.client
    - huggingface_hub.utils._http
    - h5py._conv
    - tensorflow
    - diffusers
    - urllib3.connectionpool
    - torch.distributed.nn.jit.instantiator
