name: Compile Portable Distribution
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      api:
        required: true
        type: string
      release:
        required: true
        type: boolean
jobs:
  compile-distribution:
    runs-on: ${{ inputs.os }}
    env:
      ARTIFACT_SUFFIX: ${{ inputs.api }}-
      GH_TOKEN: ${{ github.token }}
      MINIMAL_BUILD: 1
      RUN_INTEGRATION_TEST: 0
    steps:
    - uses: actions/checkout@v3
    - name: Setup Miniconda (MacOS)
      if: ${{ contains(inputs.os, 'mac') }}
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        miniconda-version: latest
    - name: Setup Miniconda (Windows/Linux)
      if: ${{ !contains(inputs.os, 'mac') }}
      uses: conda-incubator/setup-miniconda@v2.2.0
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Get Version
      id: version
      run: echo "version=$(make version)" >> $GITHUB_OUTPUT
    - name: Clean unneeded pre-installed code
      if: ${{ contains(inputs.os, 'ubuntu') }}
      run: |
        echo "Storage before:"
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        echo "Storage after:"
        df -h
    - name: Install dependencies
      run: |
        conda env update --file environments/build/${{ inputs.os }}/${{ inputs.api }}.yml --name base
    - name: Install additional TensorRT Dependencies
      if: ${{ contains(inputs.os, 'ubuntu') && contains(inputs.api, 'tensorrt') }}
      run: |
        pip install onnx==1.12 onnxruntime-gpu==1.12.1 onnx-graphsurgeon==0.3.26 tensorrt==8.6.1 --no-deps
    - name: Build XTCocoTools from Source
      if: ${{ contains(inputs.os, 'mac') }}
      run: |
        git clone https://github.com/jin-s13/xtcocoapi
        cd xtcocoapi
        make install
    - name: Install MMLab Dependencies (Windows)
      if: ${{ contains(inputs.os, 'windows') }}
      shell: bash
      run: |
        . /c/Miniconda/etc/profile.d/conda.sh
        conda activate base
        pip install -U openmim
        mim install mmengine
        mim install "git+https://github.com/open-mmlab/mmcv.git@main#egg=mmcv"
        mim install "mmdet>=3.1.0"
        mim install "mmpose>=1.1.0"
    - name: Install MMLab Dependencies (Linux/MacOS)
      if: ${{ contains(inputs.os, 'windows') }}
      run: |
        pip install -U openmim
        mim install mmengine
        mim install "git+https://github.com/open-mmlab/mmcv.git@main#egg=mmcv"
        mim install "mmdet>=3.1.0"
        mim install "mmpose>=1.1.0"
    - name: Output Environment Information for Debugging
      run: |
        conda list
        pip freeze
    - name: Clean space
      run: |
        conda clean -aqy
    - name: Output Environment Information for Debugging
      run: |
        conda list
        pip freeze
    - name: Compile Linux package
      if: ${{ !contains(inputs.os, 'windows') }} 
      run: |
        make
    - name: Compile Windows package
      if: ${{ contains(inputs.os, 'windows') }} 
      shell: bash
      run: |
        . /c/Miniconda/etc/profile.d/conda.sh
        conda activate base
        make
    - name: Clean space and split artifact
      if: ${{ contains(inputs.os, 'ubuntu') }} 
      run: |
        conda install --revision 0
        conda install make
        conda clean -aqy
        make split
    - name: Release Linux Artifact
      if: ${{ contains(inputs.os, 'ubuntu') && inputs.release }}
      run: |
        gh release upload ${{ steps.version.outputs.version }} --clobber ./enfugue-server*tar.gz*
    - name: Upload Linux artifact
      if: ${{ contains(inputs.os, 'ubuntu') && !inputs.release }}
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ inputs.os }}-${{ inputs.api }}
        path: ./enfugue-server*tar.gz*
    - name: Release Windows Artifact
      if: ${{ contains(inputs.os, 'windows') && inputs.release }}
      run: |
        gh release upload ${{ steps.version.outputs.version }} --clobber ./build/enfugue-server*zip*
    - name: Upload Windows artifact
      if: ${{ contains(inputs.os, 'windows') && !inputs.release }} 
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ inputs.os }}-${{ inputs.api }}
        path: ./build/enfugue-server*zip*
    - name: Release MacOS Artifact
      if: ${{ contains(inputs.os, 'mac') && inputs.release }}
      run: |
        gh release upload ${{ steps.version.outputs.version }} --clobber ./build/enfugue-server*tar.gz*
    - name: Upload MacOS artifact
      if: ${{ contains(inputs.os, 'mac') && !inputs.release }} 
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ inputs.os }}-${{ inputs.api }}
        path: ./build/enfugue-server*tar.gz
