name: Compile MacOS MPS Portable Distribution (Latest)
on:
  workflow_dispatch:
    inputs:
      release:
        description: Upload to a tagged release?
        required: true
        type: boolean
      dwpose:
        description: Build DWPose?
        required: true
        type: boolean
jobs:
  compile-macos-mps:
    uses: painebenjamin/app.enfugue.ai/.github/workflows/compile.yml@main
    with:
      os: macos-13
      api: mps-latest
      release: ${{ inputs.release }}
      dwpose: ${{ inputs.dwpose }}
