name: Compile Portable Distribution
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      api:
        required: true
        type: string
jobs:
  compile-distribution:
    runs-on: ${{ inputs.os }}
    env:
      RUN_INTEGRATION_TEST: 0
    steps:
    - uses: actions/checkout@v3
    - name: Setup Miniconda (MacOS)
      if: ${{ contains(inputs.os, 'mac') }}
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        miniconda-version: latest
    - name: Setup Miniconda (Windows/Linux)
      if: ${{ !contains(inputs.os, 'mac') }}
      uses: conda-incubator/setup-miniconda@v2.2.0
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Clean unneeded pre-installed code
      if: ${{ contains(inputs.os, 'ubuntu') }}
      run: |
        echo "Storage before:"
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        echo "Storage after:"
        df -h
    - name: Install dependencies
      run: |
        conda env update --file environments/build/${{ inputs.os }}/${{ inputs.api }}.yml --name base
    - name: Install additional TensorRT Dependencies
      if: ${{ contains(inputs.os, 'ubuntu') && contains(inputs.api, 'tensorrt') }}
      run: |
        pip install onnx==1.12 onnxruntime-gpu==1.12.1 onnx-graphsurgeon==0.3.26 tensorrt==8.6.1 --no-deps
    - name: Output Environment Information for Debugging
      run: |
        conda list
        pip freeze
    - name: Clean space
      run: |
        conda clean -aqy
    - name: Output Environment Information for Debugging
      run: |
        conda list
        pip freeze
    - name: Compile Linux package
      if: ${{ !contains(inputs.os, 'windows') }} 
      run: |
        make
    - name: Compile Windows package
      if: ${{ contains(inputs.os, 'windows') }} 
      shell: bash
      run: |
        . /c/Miniconda/etc/profile.d/conda.sh
        conda activate base
        make
    - name: Upload Windows artifact
      if: ${{ contains(inputs.os, 'windows') }} 
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ inputs.os }}-${{ inputs.api }}
        path: ./build/enfugue-server*zip*
    - name: Upload MacOS/Linux artifact
      if: ${{ !contains(inputs.os, 'windows') }} 
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ inputs.os }}-${{ inputs.api }}
        path: ./build/enfugue-server*tar.gz
