name: Compile Windows CUDA with TensorRT Portable Distribution
on:
  - workflow_dispatch
jobs:
  compile-windows-tensorrt:
    uses: painebenjamin/app.enfugue.ai/.github/workflows/compile.yml@main
    with:
      os: windows-latest
      api: tensorrt
