name: Compile Ubuntu CUDA Latest Portable Distribution
on:
  workflow_dispatch:
    inputs:
      release:
        description: Upload to a tagged release?
        required: true
        type: boolean
      dwpose:
        description: Build DWPose?
        required: true
        type: boolean
jobs:
  compile-ubuntu-cuda:
    uses: ./.github/workflows/compile.yml
    with:
      os: ubuntu-latest
      api: cuda-latest
      release: ${{ inputs.release }}
      dwpose: ${{ inputs.dwpose }}
