name: Compile Ubuntu CUDA with TensorRT Portable Distribution
on:
  - workflow_dispatch
jobs:
  compile-ubuntu-tensorrt:
    uses: painebenjamin/app.enfugue.ai/.github/workflows/compile.yml@main
    with:
      os: ubuntu-latest
      api: tensorrt
