name: Compile Standalone (Windows)
on:
  - workflow_dispatch
jobs:
  build:
    runs-on: windows-2019
    env:
      MINIMAL_BUILD: 1
    steps:
    - uses: actions/checkout@v3
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environments/enfugue-build-windows-tensorrt.yml --name base
    - name: Clean Space
      run: |
        conda clean -aqy
    - name: Compile Package 
      shell: bash
      run: |
        . /c/Miniconda/etc/profile.d/conda.sh
        conda activate base
        make
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: ./build/enfugue-server-*zip*
