name: Compile Windows CUDA Latest Portable Distribution
on:
  workflow_dispatch:
    inputs:
      release:
        description: Upload to a tagged release?
        required: true
        type: boolean
      dwpose:
        description: Build DWPose?
        required: true
        type: boolean
jobs:
  compile-windows-cuda:
    uses: painebenjamin/app.enfugue.ai/.github/workflows/compile.yml@main
    with:
      os: windows-latest
      api: cuda-latest
      release: ${{ inputs.release }}
      dwpose: ${{ inputs.dwpose }}
