name: Compile Windows CUDA Portable Distribution
on:
  workflow_dispatch:
    inputs:
      release:
        description: Upload to a tagged release?
        required: true
        type: boolean
      dwpose:
        description: Build DWPose?
        required: true
        type: boolean
jobs:
  compile-windows-cuda:
    uses: ./.github/workflows/compile.yml
    with:
      os: windows-latest
      api: cuda
      release: ${{ inputs.release }}
      dwpose: ${{ inputs.dwpose }}
