name: Compile Standalone (Linux)
on:
  - workflow_dispatch
jobs:
  build-linux-cuda:
    runs-on: ubuntu-latest
    env:
      MINIMAL_BUILD: 1
    steps:
    - uses: actions/checkout@v3
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Clean space
      run: |
        echo "Storage before:"
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        echo "Storage after:"
        df -h
    - name: Install dependencies
      run: |
        conda env update --file environments/enfugue-build-linux-tensorrt.yml --name base
    - name: Clean space
      run: |
        conda clean -aqy
    - name: Compile Package 
      run: |
        make
    - name: Clean space again
      run: |
        conda install --revision 0
        conda install make
        conda clean -aqy
    - name: Split artifact
      run: |
        make split
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: ./enfugue-server*.part
